# Generated by Django 6.0.3 on 2026-03-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('issue_type', models.CharField(choices=[('streetlight', 'Streetlight'), ('water', 'Water Leak'), ('waste', 'Waste & Sanitation'), ('pothole', 'Pothole'), ('environment', 'Environment & Public Health'), ('parks', 'Parks, Trees & Biodiversity'), ('electricity', 'Electricity'), ('infrastructure', 'Infrastructure Projects')], max_length=50)),
                ('issue_details', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='reported', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
